# Generated by Django 5.1 on 2024-12-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accou', '0002_usersignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='area',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='timing',
        ),
    ]
