# Generated by Django 5.1 on 2024-12-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.IntegerField(max_length=200)),
                ('bus_no', models.IntegerField(max_length=200)),
                ('number_plate', models.CharField(max_length=5)),
                ('live_location_link', models.URLField()),
            ],
        ),
    ]
