# Generated by Django 5.1 on 2024-12-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busform',
            name='bus_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='busform',
            name='route_no',
            field=models.IntegerField(),
        ),
    ]
