# Generated by Django 5.1 on 2024-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_busform_bus_no_alter_busform_route_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addroutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routenum', models.IntegerField()),
                ('areas', models.TextField()),
            ],
        ),
    ]
