# Generated by Django 5.1 on 2024-12-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_userlocred'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocred',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
